/* Generated by bin2c, do not edit manually */
#ifndef __intro_h_included
#define __intro_h_included

/* Contents of file intro_16K.raw */
extern const long int intro_16K_raw_size;
extern const unsigned char intro_16K_raw[37370];

#endif    /* __intro_h_included */
