/* Generated by bin2c, do not edit manually */
#ifndef __sample1_h_included
#define __sample1_h_included

/* Contents of file sample1_8K.raw */
extern const long int sample1_8K_raw_size;
extern const unsigned char sample1_8K_raw[10170];

#endif    /* __sample1_h_included */
