/* Generated by bin2c, do not edit manually */
#ifndef __sample2_h_included
#define __sample2_h_included

/* Contents of file sample2_16K.raw */
extern const long int sample2_16K_raw_size;
extern const unsigned char sample2_16K_raw[19410];

#endif    /* __sample2_h_included */
