/* Generated by bin2c, do not edit manually */
#ifndef __sample3_h_included
#define __sample3_h_included

/* Contents of file sample3_31K.raw */
extern const long int sample3_31K_raw_size;
extern const unsigned char sample3_31K_raw[34830];

#endif    /* __sample3_h_included */
